# 데이터 전처리

In [2]:
import pandas as pd
import re
import numpy as np

In [23]:
df = pd.read_csv('네이버맛집_이미지추가.csv', header='infer', engine='python', encoding='utf-8-sig', sep=',')

In [24]:
df['Menu'][24]

'50,000원\r\n스시오마카세\r\n50,000원\r\n점심\r\n80,000원\r\n저녁'

In [26]:
# Address열 전처리
for i, df_Address in enumerate(df.Address):
    df.loc[i, 'Address'] = re.sub('지도보기', '', df_Address)

In [27]:
# Menu 열 전처리1
for i, df_Menu in enumerate(df.Menu):
    df.loc[i, 'Menu'] = re.sub('원\r\n', '원 ', df_Menu)

In [28]:
# Menu 열 전처리2
for i, df_Menu in enumerate(df.Menu):
    df.loc[i, 'Menu'] = re.sub('대표\r\n', '', df_Menu)

In [29]:
# Menu 열 전처리3
for i, df_Menu in enumerate(df.Menu):
    df.loc[i, 'Menu'] = re.sub('\r\n더보기', '', df_Menu)

In [30]:
# Menu 열 전처리4
for i, df_Menu in enumerate(df.Menu):
    df.loc[i, 'Menu'] = re.sub('\r\n메뉴판.*', '', df_Menu)

In [31]:
# Menu 열 전처리5
for i, df_Menu in enumerate(df.Menu):
    df.loc[i, 'Menu'] = re.sub('메뉴판.*', '', df_Menu)

In [32]:
# Menu 열 전처리6
for i, df_Menu in enumerate(df.Menu):
    df.loc[i, 'Menu'] = re.sub('메뉴.*\r\n', '', df_Menu)

In [33]:
# age 열 전처리
ages = ['10', '20', '30', '40', '50', '60']
for age in ages:    
    for i, df_prefer_per_age in enumerate(df[age]):
        try:
            df.loc[i, age] = re.sub('%;', '' , re.sub('height: ', '',df_prefer_per_age))
        except:
            df.loc[i, age] = ''

In [34]:
# 성별열 전처리
genders = ['Female', 'Male']
for gender in genders:
    for i, df_prefer_per_gender in enumerate(df[gender]):
        try:
            df.loc[i, gender] = re.sub('%', '', df_prefer_per_gender)
        except:
            df.loc[i, gender] = ''

In [35]:
# Store_name에 Category와 중복된 부분 제거
for i, df_Store_name in enumerate(df.Store_name):
    if str(df.loc[i, 'Category']) != 'nan':
        df.loc[i, 'Store_name'] = re.sub(df.loc[i, 'Category'], '', df_Store_name)

In [45]:
# 바나프레소 오류 수정
for i, df_Category in enumerate(df.Category):
    if re.search(str(df_Category), '바나프레소'):
        df.loc[i, 'Category'] = re.sub('바나프레소', '카페', df_Category)
        df.loc[i, 'Store_name'] = '바나프레소' + df.loc[i, 'Store_name']

In [9]:
# Review 컬럼 , 제거
for i, df_Review in enumerate(df.Review):
    df.loc[i, 'Review'] = re.sub(',', '', df_Review)

In [10]:
df

,Store_name,Category,Review,TV,Biztel,Address,Menu,Homepage,페이스북,인스타그램,...,Desc,10,20,30,40,50,60,Female,Male,Images
0,클로리스 티 앤 커피,홍차전문점,3591,NaN,02-553-7523,서울 강남구 테헤란로 152\r\n지번역삼동 737 강남파이낸스센터 지하1층,"5,800원 밀크티\r\n4,800원 허브\r\n4,500원 아메리카노\r\n5,2...",NaN,NaN,NaN,...,고풍스러운 인테리어의 티 전문 카페입니다. 순수함을 상징하는 여신의 이름에서 카페 ...,40.032,78.9417,66.373,45.4563,30.3777,34.3507,54,46,['https://search.pstatic.net/common/?autoRotat...
1,돝고기506,돼지고기구이,2927,NaN,02-6933-9506,서울 강남구 역삼로17길 53\r\n지번역삼동 739-13,"17,000원 A506 숙성 삼겹살 150g\r\n17,000원 i506 숙성 목살...",https://catchtable.co.kr/widget/reservation?sh...,NaN,http://www.instagram.com/dot506_official,...,"돝고기506\r\n저희 돝고기는 21일, 총 506시간을 숙성하고 51번의 과정을 ...",6.92067,81.32,81.8753,78.1793,44.576,34.3973,53,47,['https://search.pstatic.net/common/?autoRotat...
2,빌즈 강남,NaN,10527,NaN,02-568-1353,서울 강남구 테헤란로 142\r\n지번역삼동 736-1 아크플레이스 2층,"19,800원 빌즈 리코타 핫케이크\r\n24,000원 풀오지\r\n22,000원 ...",http://www.billskorea.com,NaN,http://www.instagram.com/billskorea,...,"*평일과 주말, 공휴일 모두 오후 1시부터 오후 2시 30분까지 예약을 받지 않습니...",34.547,76.7583,71.8453,64.2587,45.0967,44.004,60,40,['https://search.pstatic.net/common/?autoRotat...
3,마마스 역삼점,카페,72,NaN,02-538-1280,서울 강남구 논현로85길 7\r\n지번역삼동 738-6,"13,900원 리코타치즈샐러드\r\n9,800원 모짜렐라 토마토 파니니\r\n7,4...",http://cafemamas.co.kr,NaN,NaN,...,"샌드위치 전문 카페 카페마마스의 역삼 점. 간단히 샌드위치, 빵과 음료를 즐길 수 ...",32.3284,99.2662,88.6587,60.7369,41.776,41.8809,56,44,['https://search.pstatic.net/common/?autoRotat...
4,백제원역삼지에프시점,한식,3047,NaN,02-2051-1122,서울 강남구 테헤란로 152\r\n지번역삼동 737 강남파이낸스센터,"15,000~20,000원 런치정찬\r\n82,000~98,000원 백제원 스페셜 ...",http://didimworld.co.kr/,https://www.facebook.com/DidimDining/,NaN,...,NaN,35.7591,80.9862,83.7978,82.9262,94.3298,81.6116,46,54,['https://search.pstatic.net/common/?autoRotat...
5,핑크솔740,이탈리아음식,4875,NaN,02-558-0740,서울 강남구 테헤란로20길 25\r\n지번역삼동 740,"19,000원 핑크크림파스타\r\n19,000원 쉬림프로제파스타\r\n37,000원...",http://www.instagram.com/pinksol_740,NaN,NaN,...,"핑크솔 740은 화덕에 구운 피자, 파스타, 플레이트 메뉴, 맥주, 와인을 즐길 ...",35.9862,98.3898,86.8884,54.8227,41.58,43.6787,51,49,['https://search.pstatic.net/common/?autoRotat...
6,피키이터 역삼점,브런치,226,NaN,02-558-5465,서울 강남구 테헤란로26길 14\r\n지번역삼동 736-58 B1,"8,000원 연어샐러드\r\n6,000원 아보카도토스트\r\n8,000원 아보카도계...",http://www.instagram.com/pickyeater_yeoksam/,NaN,NaN,...,"'eat better, feel better'\r\n피키이터는 깐깐한 입맛으로 정직...",40.4235,99.103,88.1315,73.738,56.4925,61.086,59,41,['https://search.pstatic.net/common/?autoRotat...
7,오발탄 역삼점,"곱창,막창,양",7,NaN,02-2051-7775,서울 강남구 논현로86길 12\r\n지번역삼동 725,"34,000원 특양구이",http://www.hiobaltan.com/,NaN,NaN,...,깔끔하게 입맛을 사로잡는 오발탄만의 독특한 소스와\r\n지방분이 전혀 없는 쫄깃한 ...,29.5351,74.1356,76.86,96.396,85.9564,66.2898,45,55,[]
8,남도애꽃,한정식,3457,생생정보통,02-561-3955,서울 강남구 테헤란로14길 16\r\n지번역삼동 823-30 라인빌딩,"28,000원 보리굴비 한상(점심)\r\n60,000원 원앙 코스\r\n29,000...",http://www.남도애꽃.kr/,NaN,NaN,...,맛의 고장 남도의 별미를 한정식 코스로 선보이는 남도 한정식 매장입니다. \r\n김...,26.453,56.8723,62.1833,77.399,75.554,69.0987,45,55,['https://search.pstatic.net/common/?autoRotat...
9,바스버거 역삼점,NaN,2181,NaN,02-568-6654,서울 강남구 테헤란로26길 10\r\n지번역삼동 736-55 성보빌딩 지하1층,"6,300원 바스버거\r\n7,400원 바스치킨버거\r\n7,700원 하와이안버거\...",http://www.basburger.net/,http://facebook.com/basburger.kr/,http://www.instagram.com/basburger_/,...,부담없는 가격에 만족스러운 수제버거를 제공합니다.\r\n수제버거를 밀크쉐이크 그리고...,47.164,96.741,88.163,78.5445,60.4285,59.385,50,50,[]
10,강남목장,"육류,고기요리",3177,맛있는녀석들,02-562-7003,서울 강남구 논현로86길 34\r\n지번역삼동 725-25 역삼포커스빌딩,"39,000원 업진살\r\n39,000원 생등심\r\n39,000원 생갈비살\r\n...",http://www.gncorral.com/,NaN,NaN,...,"강남 우수한 한우 구이 전문집, 단체룸, 발렛 파킹, 회식, 접대, 코키지 프리, ...",26.0702,69.2964,88.3431,94.5031,52.1804,53.7858,44,56,['https://search.pstatic.net/common/?autoRotat...
11,고갯마루,한식,36,NaN,NaN,서울 강남구 테헤란로28길 27\r\n지번역삼동 725-12,NaN,NaN,NaN,NaN,...,NaN,25,83.6435,89.5195,73.319,46.998,53.5835,48,52,[]
12,샐러디 역삼점,"다이어트,샐러드",971,NaN,02-565-4066,서울 강남구 논현로85길 13\r\n지번역삼동 739 역삼동빌딩,"5,400원 콥 샐러디\r\n8,900원 아보카도연어 샐러디\r\n5,700원 시저...",http://www.saladykorea.com/,NaN,NaN,...,"샐러드, 곡물빵, 샌드위치, 랩샐러드, 음료\r\n건강한 패스트푸드 샐러디 역삼점입니다.",48.4244,93.5813,74.0858,51.5311,39.5591,36.696,59,41,['https://search.pstatic.net/common/?autoRotat...
13,마구로젠 역삼점,NaN,210,좋은아침,02-573-2777,서울 강남구 논현로86길 32\r\n지번역삼동 725-24 삼우빌딩,"80,000원 골드32,000원 점심참치특정식\r\n55,000원 스페셜\r\n68...",http://magurozen.modoo.at,NaN,NaN,...,마구로젠은 역삼점과 신사점직영으로만 운영 하고 있습니다.\r\n300kg이상의 참다...,15.2324,64.208,86.6991,91.2693,52.8542,53.0422,41,59,['https://search.pstatic.net/common/?autoRotat...
14,강남보물섬,생선회,1177,NaN,02-566-3563,서울 강남구 테헤란로20길 11-1\r\n지번역삼동 736-19,"45,000원 모듬회(중)\r\n85,000원 모듬회(대)\r\n45,000원 광어...",NaN,NaN,NaN,...,강남역 역삼1동에 위치한 횟집,23.5284,72.8609,88.132,90.2231,56.0831,52.9236,43,57,[]
15,베이징코야 역삼동점,중식당,151,생생정보통,02-733-5292,서울 강남구 논현로86길 20\r\n지번역삼동 725-9 봉강빌딩 1층,"69,000원 북경오리 1마리\r\n30,000원 오리구이\r\n65,000원 특송...",NaN,NaN,NaN,...,중국식 북경오리 전문점 베이징코야의 강남 지점입니다. 본점은 수송동에 위치하고 있지...,32.0435,73.6575,97.0895,87.5515,96.258,87.9475,44,56,['https://search.pstatic.net/common/?autoRotat...
16,노아베이커리 GFC점,NaN,3591,NaN,02-558-4100,서울 강남구 테헤란로 152\r\n지번역삼동 737 B1,"2,900원 아메리카노",NaN,NaN,NaN,...,지친 일상에서 벗어나 감성과 휴식을 선사하는\r\n유러피안 라이프 스타일의 베이커리...,15.332,71.1493,53.3993,33.46,11.6507,10.186,60,40,['https://search.pstatic.net/common/?autoRotat...
17,스타벅스 역삼역점,카페,106,NaN,02-758-8314,서울 강남구 테헤란로 145\r\n지번역삼동 646-15 우신빌딩,"4,100원 아메리카노(Tall)",http://www.istarbucks.co.kr/,http://www.facebook.com/starbuckskorea,http://www.instagram.com/starbuckskorea,...,NaN,42.3815,91.4295,80.6485,67.282,51.5115,45.9655,56,44,['https://search.pstatic.net/common/?autoRotat...
18,신동궁 역삼본점,감자탕,172,VJ특공대,02-555-3782,서울 강남구 테헤란로10길 11\r\n지번역삼동 823-41,"28,000원 감자탕(소)\r\n28,000원 뼈 숯불구이(소)\r\n28,000원...",NaN,NaN,NaN,...,"육질이 우수한 최상의 목뼈와 국내산 사골로 장시간 우려낸 진한 국물 맛에, 신동궁만...",33.3533,94.3013,86.8404,70.3662,54.7493,53.4796,48,52,['https://search.pstatic.net/common/?autoRotat...
19,가조쿠,일식당,1341,NaN,02-556-2177,서울 강남구 테헤란로25길 6-7\r\n지번역삼동 642-4 지하 1층,"6,500원 가케우동\r\n6,500원 붓가케우동\r\n9,500원 사케동\r\n1...",NaN,NaN,NaN,...,"사누키우동 일본식 메밀소바 ,, 그리고 일본 가정식 전문점 입니다. 저녁시간대에는 ...",49.5225,95.406,80.1545,70.457,57.8765,54.012,51,49,['https://search.pstatic.net/common/?autoRotat...
20,에그드랍 역삼점,샌드위치,321,NaN,02-566-1611,서울 강남구 논현로85길 52\r\n지번역삼동 735-17 1층 101호,"3,900원 베이컨 더블 치즈 샌드위치\r\n4,600원 아보홀릭 샌드위치\r\n2...",NaN,NaN,NaN,...,에그드랍은 현대인의 라이프스타일에 맞춘 프리미엄 Value를 제공한는 브랜드 입니다...,60.48,95.542,91.307,83.4525,53.879,54.5075,62,38,[]
21,루프탑 클라우드,NaN,777,NaN,02-2050-6035,서울 강남구 테헤란로25길 10\r\n지번역삼동 642,"270,000원 그레이 구스 SET\r\n260,000원 돈 훌리오 SET\r\n2...",http://urbandelight.co.kr/rooftop-kloud/,NaN,NaN,...,"*평일,일요일 18:00 - 01:00\r\n 음식 라스트오더 11:30, 음료 라...",31.7893,91.6644,78.5929,66.8844,50.0049,44.776,51,49,['https://search.pstatic.net/common/?autoRotat...
22,모터시티,양식,542,NaN,02-2051-8877,서울 강남구 테헤란로 142\r\n지번역삼동 736-1,"23,900원 JACKSON 5\r\n23,900원 MANIMAL BBQ\r\n24...",http://www.instagram.com/motorcitykorea,http://www.facebook.com/motorcitykorea,NaN,...,모터시티는 팀 매니멀의 다섯 번째 레스토랑입니다.\r\n모터시티의 아이디어는 팀 매...,25,87.303,87.2215,72.228,55.2575,58.0665,53,47,['https://search.pstatic.net/common/?autoRotat...
23,롱브레드 베이커리,샌드위치,1561,NaN,02-566-1253,서울 강남구 테헤란로22길 15\r\n지번역삼동 736-44 건축문화사옥,"9,500원 롱브레드 파니니\r\n11,500원 연어 아보카도 샐러드\r\n8,50...",https://www.instagram.com/longbread_bakery,NaN,NaN,...,"다른 곳에서 맛 볼 수 없는 베이커리와 샌드위치.\r\n앙버터, 치아버터, 깜빠뉴,...",28.3329,89.1658,79.6182,66.7191,45.7089,38.7182,59,41,['https://search.pstatic.net/common/?autoRotat...
24,스시산원 청,"초밥,롤",176,NaN,02-538-5550,서울 강남구 논현로85길 52\r\n지번역삼동 735-20 역삼푸르지오시티 2층 2...,"50,000원 스시오마카세\r\n50,000원 점심\r\n80,000원 저녁",NaN,NaN,NaN,...,스시오마카세 전문점,27.2855,89.62,90.063,78.28,64.613,62.3855,45,55,[]
25,파크루안 역삼점,NaN,304,NaN,02-562-5565,서울 강남구 논현로 430\r\n지번역삼동 726 아세아빌딩 지하 1층,"8,000원 웰빙삼선콩자장면\r\n12,000원 왕갈비짬뽕\r\n23,000원 찹쌀...",http://www.parkruan.com,NaN,NaN,...,프리미엄 차이니스 레스토랑 파크루안 역삼점입니다. 식사와 요리부터 다양한 가격대의 ...,35.5935,75.7975,82.545,86.066,98.874,97.309,46,54,['https://search.pstatic.net/common/?autoRotat...
26,생어거스틴 강남파이낸스점,NaN,2185,NaN,02-553-5101,서울 강남구 테헤란로 152\r\n지번역삼동 737 강남파이낸스센터,"18,000원 왕새우 팟타이\r\n15,000원 스파이시 타이 칠리 누들\r\n14...",http://www.augustin.co.kr/,NaN,NaN,...,"태국 현지 쉐프가 책임지는 바로 그 맛! \r\n팟타이, 똠얌꿍, 뿌팟봉커리등\r\...",25,93.68,84.908,64.6775,44.289,44.0895,54,46,['https://search.pstatic.net/common/?autoRotat...
27,송추가마골 인어반 강남점,NaN,1045,NaN,02-554-9290,서울 강남구 테헤란로 134\r\n지번역삼동 735-3 포스코타워 역삼 지하 1층,"11,000원 뚝배기갈비탕\r\n39,000원 가마골갈비\r\n21,000원 한돈돼...",http://www.gamagoll.com/,https://www.facebook.com/scgamagoll/,http://www.instagram.com/scgamagoll/,...,"프리미엄 한우, 양념갈비, 돼지구이, 갈비탕, 런치쌈밥정식 등을 깔끔하고 고급스런 ...",25,63.355,83.448,91.68,83.211,95.1965,47,53,[]
28,연안식당 역삼점,"해물,생선요리",622,NaN,02-562-6092,서울 강남구 논현로85길 13\r\n지번역삼동 739 근영빌딩 2층,"변동\r\n꼬막비빔밥\r\n12,000원 꽃게살비빔밥\r\n12,000원 꽃게뚝배기...",http://yeonansikdang.co.kr/,NaN,NaN,...,바닷가 옆 길 여느 식당에서 맛 보았던 신선한 해산물 요리들.\r\n그렇게 신선했던...,25,71.153,86.883,94.627,77.377,72.3895,50,50,[]
29,교센,NaN,2967,NaN,02-501-2334,서울 강남구 테헤란로16길 9\r\n지번역삼동 735-29 1층,"45,000원 숙성회 코스 1인\r\n18,000원 간장새우\r\n20,000원 스...",NaN,NaN,NaN,...,"숙성회 코스(무한리필)\r\n1인 45,000원\r\n모둠초밥 20,000원\r\n...",25,76.99,90.7355,96.438,58.739,53.457,42,58,['https://search.pstatic.net/common/?autoRotat...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4965,본 삼성차관아파트점 삼성중앙역,죽,2,NaN,02-555-0686,서울 강남구 봉은사로 474\r\n지번삼성동 117 쌍용 플래티넘,"11,000원 전복죽\r\n16,000원 트러플 전복죽\r\n15,000원 삼계전복...",http://www.bonjuk.co.kr/,NaN,NaN,...,NaN,25,67.9995,79.399,80.347,67.01,25,53,47,[]
4966,서초동연가 별관,"육류,고기요리",16,NaN,02-591-0281,서울 서초구 사평대로56길 14\r\n지번서초동 1302-39 동원빌딩 1층,"25,000원 전통육회\r\n40,000원 전통육회+사시미",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
4967,태영생막창 서울본점,"곱창,막창,양",252,NaN,NaN,서울 강남구 논현로38길 18\r\n지번도곡동 412-5,"12,000원 돼지생막창 150g\r\n16,000원 소막창 150g\r\n12,0...",NaN,NaN,NaN,...,NaN,25,72.7935,79.5435,79.4825,64.7665,25,47,53,[]
4968,마망갸또 신사동점,케이크전문,643,NaN,070-4353-5860,서울 강남구 압구정로10길 30-12\r\n지번신사동 524-27,"5,500원 카라멜 롤케이크\r\n5,500원 카라멜사케라떼\r\n6,500원 오레...",http://www.mamangt.com/,NaN,NaN,...,"가로수길 디저트, 가로수길 빙수, 카라멜 빙수, 카라멜 전문점!",47.3923,97.3677,76.3343,52.6253,39.964,36.1957,63,37,['https://search.pstatic.net/common/?autoRotat...
4969,문어세상 양재점,"해물,생선요리",31,모닝와이드,02-575-0995,서울 서초구 강남대로 188\r\n지번양재동 15-3 화승빌딩,"120,000원 해천탕(닭) 스페셜\r\n100,000원 해천탕(닭) 對\r\n80...",NaN,NaN,NaN,...,NaN,25,50.3465,78.367,92.762,91.4915,93.827,40,60,[]
4970,마봉 논현언주역점,양꼬치,26,NaN,02-518-1515,서울 강남구 봉은사로29길 13\r\n지번논현동 234-3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
4971,메차쿠차 강남역점,일식당,81,NaN,02-3481-3767,서울 서초구 강남대로69길 11\r\n지번서초동 1308-1 삼미빌딩,"8,000원 우동정식\r\n9,000원 김치나베돈가스\r\n10,000원 모밀정식\...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
4972,참숯주먹생고기,"육류,고기요리",9,NaN,02-6401-5132,서울 강남구 역삼로1길 20\r\n지번역삼동 831-31 2층,"35,000원 한우등심\r\n25,000원 진갈비살\r\n15,000원 안창살\r\...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
4973,바나프레소 대치은마점,카페,71,NaN,070-8998-8921,서울 강남구 도곡로 451\r\n지번대치동 941-22 한나빌딩 1층,"1,500원 아메리카노",http://www.instagram.com/banapresso,NaN,NaN,...,바나프레소가 공부에 지친 학생들과 자녀분들을 기다리는 부모님을 위해 대치동 넓은 매...,93.427,77.393,52.2345,96.6265,74.5405,25,60,40,[]
4974,해우름,생선회,27,NaN,02-6080-1113,서울 서초구 바우뫼로37길 38\r\n지번양재동 16-1,"9,000원 낙지볶음\r\n25,000원 활어숙성회 스페셜\r\n40,000원 활어...",NaN,NaN,NaN,...,숙성회는 쫄깃하고 탱탱한 식감과 감칠맛을 느낄 수 있습니다. 신선한 활어를 잡아서 ...,25,64.83,88.363,92.0155,80.56,78.4745,40,60,[]
4975,삼국지,중식당,25,NaN,02-549-2339,서울 강남구 언주로134길 6\r\n지번논현동 115-22,NaN,http://blog.naver.com/kkajc3/110138973966,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['https://search.pstatic.net/common/?autoRotat...
4976,부산아지매 학동역점,국밥,28,NaN,02-553-9882,"서울 강남구 학동로 165\r\n지번논현동 58-2 마일스디오빌 1층 112,113호","7,000원 아지매국밥",http://www.busanajimae.com/,https://www.facebook.com/busan9882/,https://www.instagram.com/busan_ajimae/,...,"주식회사 제이엘푸드(JL FOOD co.,Ltd.)는 지역 향토음식개발 전문업체로서...",25,86.2695,80.522,71.568,57.4355,25,47,53,[]
4977,짝꿍,떡볶이,541,NaN,02-537-6836,서울 서초구 서초대로53길 7\r\n지번서초동 1695-7 효성빌딩 지하 1층 짝꿍떡볶이,"12,000원 2인세트\r\n21,000원 4인세트\r\n4,000원 1인추가\r\...",NaN,NaN,NaN,...,밥이 되는 떡볶이 든든한 짝꿍떡볶이 입니다.\r\n주인장이 직접 만든 뒷맛이 깔끔한...,62.718,86.216,83.0185,78.9125,46.0315,45.0555,58,42,['https://search.pstatic.net/common/?autoRotat...
4978,커피빈 삼성전자강남사옥점,카페,4,NaN,02-2055-1142,서울 서초구 서초대로74길 11\r\n지번서초동 1320-10 삼성전자 서초사옥,"4,800원 아메리카노 S\r\n5,300원 카페라떼 S",http://www.coffeebeankorea.com/,http://www.facebook.com/thecoffeebeankorea,http://www.instagram.com/coffeebeankorea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
4979,진고래,한식,8,NaN,02-566-0231,서울 강남구 선릉로86길 18\r\n지번대치4동 897-22,"27,000원 참복지리.탕\r\n60,000원 참복불고기\r\n60,000원 참복찜...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
4980,멜리멜로,베이커리,711,NaN,02-588-2435,서울 서초구 사임당로19길 6\r\n지번서초동 1648-2 1층 멜리멜로,"2,400원 휘낭시에\r\n9,000원 심쿵멜로\r\n4,000원 아메리카노\r\n...",http://instagram.com/melimelo.dessert,NaN,NaN,...,멜리멜로는 (MÉLI MÉLO) 뒤죽박죽이란 뜻의 불어로 파리 르 꼬르동 블루 출신...,59.5105,93.293,78.6215,64.2775,48.4755,49.213,61,39,['https://search.pstatic.net/common/?autoRotat...
4981,겟 올라잇바(BAR),바(BAR),106,NaN,010-3065-0895,서울 강남구 도산대로57길 18\r\n지번청담동 89-5,"340,000원 Glenfiddich 12y\r\n340,000원 Balvenie ...",http://instagram.com/getallright.cheongdam/,NaN,NaN,...,"SIGNATURE COCKRAIL\r\nGet All Mule / 25,000\r\...",20.9431,95.8258,95.2178,73.6093,48.6404,53.2213,53,47,[]
4982,더 트리하우스바(BAR),바(BAR),1095,NaN,02-556-2017,서울 강남구 삼성로104길 21\r\n지번삼성동 148-13 5층,변동\r\nClassic Cocktail\r\n변동\r\nWhiskey,http://blog.naver.com/thetreehouse2017,NaN,NaN,...,"THE Tree House 몰트바 & 루프탑바 \r\n\r\nWhisky, Vodk...",25,91.261,81.915,70.1715,46.0745,25,49,51,['https://search.pstatic.net/common/?autoRotat...
4983,청춘극장 쪽갈비,"육류,고기요리",65,NaN,02-555-2133,서울 강남구 봉은사로72길 6\r\n지번삼성동 115-32,"15,000원 양념쪽갈비\r\n15,000원 매운쪽갈비\r\n14,000원 항정껍데...",https://chungchun6161.modoo.at,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
4984,이비스스타일앰배서더강남 프레쉬365다이닝,NaN,1637,NaN,02-3011-8120,서울 강남구 삼성로 431\r\n지번대치동 893-1 이비스 스타일 앰배서더 강남 ...,"22,000원 조식뷔페\r\n35,000원 런치 뷔페\r\n45,000원 주말 런치...",https://www.ambatel.com/ibisstyles/gangnam/ko/...,NaN,NaN,...,세계 10대 슈퍼푸드가 다채롭게 조리된 메뉴로 가득한 Fresh 365 Dining...,46.7995,77.525,88.8915,93.1235,74.8805,74.6155,51,49,['https://search.pstatic.net/common/?autoRotat...
4985,자금성,중식당,181,NaN,050-4109-2917,서울 강남구 학동로67길 7\r\n지번청담동 44-7,"6,000원 짜장면\r\n6,500원 짬뽕\r\n20,000원 탕수육\r\n21,0...",http://412017.4tong.co.kr/service1/,NaN,NaN,...,◈ 영업시간 :낮10시~저녁9시 ◈\r\n \r\n◈ 배달지역...,32.644,57.6929,69.0431,84.8333,91.3889,74.1827,49,51,['https://search.pstatic.net/common/?autoRotat...
4986,우와,일식당,4525,NaN,070-8833-7336,서울 강남구 강남대로158길 17\r\n지번신사동 508-8 1층,"12,500원 돼지오코노미야끼&야끼소바\r\n16,000원 철판 꽃갈비살 100g\...",NaN,NaN,NaN,...,NaN,48.9653,89.8076,71.4373,53.7742,45.9307,40.8276,54,46,[]
4987,스테프핫도그 선릉역점,NaN,81,NaN,02-2183-1097,서울 강남구 테헤란로 322\r\n지번역삼동 707-34 한신인터밸리24빌딩 B113호,"5,700원 스테프 핫도그\r\n5,500원 치즈 온 불고기\r\n6,600원 치즈...",NaN,NaN,NaN,...,NaN,25,89.122,77.5855,67.11,36.5705,25,55,45,[]
4988,할리스커피 학동역점,카페,19,NaN,070-4700-6699,서울 강남구 학동로 219\r\n지번논현동 89-22 국제빌딩,"4,100원 카페 아메리카노\r\n4,600원 카페 라떼\r\n5,400원 바닐라 ...",http://www.hollys.co.kr/,https://www.facebook.com/EnjoyHollys,https://www.instagram.com/hollyscoffeekr,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
4989,뻐꾸기,포장마차,202,NaN,02-512-6798,서울 강남구 도산대로17길 4\r\n지번신사동 561-17,"16,000원 통마늘 닭똥집\r\n17,000원 낙지 떡볶이\r\n17,000원 알...",NaN,NaN,NaN,...,벽면에 온갖 낙서가 되어 있어 정겨운 느낌을 주는 술집입니다. 분위기처럼 인심 넘치...,49.4249,93.964,74.5267,56.3036,39.6729,43.6911,55,45,['https://search.pstatic.net/common/?autoRotat...
4990,테이블스푼 청담점,"도시락,컵밥",205,NaN,02-518-3585,서울 강남구 선릉로 660\r\n지번삼성동 8-2 브라운스톤 레전드상가 1층 113호,"8,000원 한입도시락_단품A\r\n10,000원 한입도시락_단품B\r\n20,00...",http://tbspchungdahm.modoo.at/,NaN,NaN,...,테이블스푼 수제도시락 (청담동) \r\n\r\n★ 원하는 가격대로! 맞춤 도시락 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['https://search.pstatic.net/common/?autoRotat...
4991,송탄부대찌개본점,"찌개,전골",133,NaN,02-541-2446,서울 강남구 도산대로 166\r\n지번논현동 7-1,"12,000원 특부대찌개\r\n12,000원 만두부대찌개\r\n12,000원 카레부...",http://blog.naver.com/songtanbudae,NaN,NaN,...,20년 전통 신사동 맛집 송탄부대찌개 입니다\r\n직접 우려낸 사골육수의 진한 ...,52.509,85.106,87.1045,85.129,65.5595,66.2855,48,52,['https://search.pstatic.net/common/?autoRotat...
4992,서초생곱창,"곱창,막창,양",51,NaN,02-583-5663,서울 서초구 서초대로54길 11\r\n지번서초동 1670-1,"23,000원 곱창1인분\r\n24,000원 소 양구이 1인분\r\n18,000원 ...",NaN,NaN,NaN,...,NaN,48.842,82.1595,81.914,83.847,66.5935,70.0575,49,51,[]
4993,마이디어,케이크전문,10,NaN,010-9959-0525,서울 강남구 강남대로118길 55\r\n지번논현동 180-16 세림빌딩 2층,"40,000원 레터링 케이크\r\n85,000원 플라워 케이크",https://www.instagram.com/mydearcake_korea,NaN,NaN,...,마이디어 케이크는\r\n2014년부터 100% 우유 버터를 베이스로 한 버터크림 케...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['https://search.pstatic.net/common/?autoRotat...
4994,영동회관,"육류,고기요리",103,NaN,02-6084-0250,서울 서초구 강남대로30길 28\r\n지번양재동 17-1 1층,"12,000원 급냉 삼겹살\r\n7,000원 청국장찌개\r\n12,000원 키조개 ...",NaN,NaN,NaN,...,"1985년 양재동 말죽거리에 있었던 영동회관을 모티브로 네이밍하였으며,\r\n그 당...",25,64.386,85.9535,84.239,66.8435,25,44,56,[]

In [46]:
df.to_csv("네이버맛집_전처리.csv", index=False, encoding='utf-8-sig')

# 결측치 처리

In [14]:
df = pd.read_csv('네이버맛집_전처리.csv', header='infer', engine='python', encoding='utf-8-sig', sep=',')

In [15]:
df = df.fillna('NaN')

In [23]:
df

,Store_name,Category,Review,TV,Biztel,Address,Menu,Homepage,페이스북,인스타그램,...,20,30,40,50,60,Female,Male,Images,Price,Avr
0,클로리스 티 앤 커피,홍차전문점,3591,NaN,02-553-7523,서울 강남구 테헤란로 152\r\n지번역삼동 737 강남파이낸스센터 지하1층,"5,800원 밀크티\r\n4,800원 허브\r\n4,500원 아메리카노\r\n5,2...",NaN,NaN,NaN,...,78.9417,66.373,45.4563,30.3777,34.3507,54,46,['https://search.pstatic.net/common/?autoRotat...,5800 4800 4500 5200 10000,6060.000000
1,돝고기506,돼지고기구이,2927,NaN,02-6933-9506,서울 강남구 역삼로17길 53\r\n지번역삼동 739-13,"17,000원 A506 숙성 삼겹살 150g\r\n17,000원 i506 숙성 목살...",https://catchtable.co.kr/widget/reservation?sh...,NaN,http://www.instagram.com/dot506_official,...,81.32,81.8753,78.1793,44.576,34.3973,53,47,['https://search.pstatic.net/common/?autoRotat...,17000 17000 19000 32000 37000,24400.000000
2,빌즈 강남,NaN,10527,NaN,02-568-1353,서울 강남구 테헤란로 142\r\n지번역삼동 736-1 아크플레이스 2층,"19,800원 빌즈 리코타 핫케이크\r\n24,000원 풀오지\r\n22,000원 ...",http://www.billskorea.com,NaN,http://www.instagram.com/billskorea,...,76.7583,71.8453,64.2587,45.0967,44.004,60,40,['https://search.pstatic.net/common/?autoRotat...,19800 24000 22000 24000,22450.000000
3,마마스 역삼점,카페,72,NaN,02-538-1280,서울 강남구 논현로85길 7\r\n지번역삼동 738-6,"13,900원 리코타치즈샐러드\r\n9,800원 모짜렐라 토마토 파니니\r\n7,4...",http://cafemamas.co.kr,NaN,NaN,...,99.2662,88.6587,60.7369,41.776,41.8809,56,44,['https://search.pstatic.net/common/?autoRotat...,13900 9800 7400 5200,9075.000000
4,백제원역삼지에프시점,한식,3047,NaN,02-2051-1122,서울 강남구 테헤란로 152\r\n지번역삼동 737 강남파이낸스센터,"15,000~20,000원 런치정찬\r\n82,000~98,000원 백제원 스페셜 ...",http://didimworld.co.kr/,https://www.facebook.com/DidimDining/,NaN,...,80.9862,83.7978,82.9262,94.3298,81.6116,46,54,['https://search.pstatic.net/common/?autoRotat...,15000 20000 82000 98000 87000 98000 30000 5400...,55000.000000
5,핑크솔740,이탈리아음식,4875,NaN,02-558-0740,서울 강남구 테헤란로20길 25\r\n지번역삼동 740,"19,000원 핑크크림파스타\r\n19,000원 쉬림프로제파스타\r\n37,000원...",http://www.instagram.com/pinksol_740,NaN,NaN,...,98.3898,86.8884,54.8227,41.58,43.6787,51,49,['https://search.pstatic.net/common/?autoRotat...,19000 19000 37000 18000 20000,22600.000000
6,피키이터 역삼점,브런치,226,NaN,02-558-5465,서울 강남구 테헤란로26길 14\r\n지번역삼동 736-58 B1,"8,000원 연어샐러드\r\n6,000원 아보카도토스트\r\n8,000원 아보카도계...",http://www.instagram.com/pickyeater_yeoksam/,NaN,NaN,...,99.103,88.1315,73.738,56.4925,61.086,59,41,['https://search.pstatic.net/common/?autoRotat...,8000 6000 8000 9500 5500,7400.000000
7,오발탄 역삼점,"곱창,막창,양",7,NaN,02-2051-7775,서울 강남구 논현로86길 12\r\n지번역삼동 725,"34,000원 특양구이",http://www.hiobaltan.com/,NaN,NaN,...,74.1356,76.86,96.396,85.9564,66.2898,45,55,[],34000,34000.000000
8,남도애꽃,한정식,3457,생생정보통,02-561-3955,서울 강남구 테헤란로14길 16\r\n지번역삼동 823-30 라인빌딩,"28,000원 보리굴비 한상(점심)\r\n60,000원 원앙 코스\r\n29,000...",http://www.남도애꽃.kr/,NaN,NaN,...,56.8723,62.1833,77.399,75.554,69.0987,45,55,['https://search.pstatic.net/common/?autoRotat...,28000 60000 29000 35000 32000,36800.000000
9,바스버거 역삼점,NaN,2181,NaN,02-568-6654,서울 강남구 테헤란로26길 10\r\n지번역삼동 736-55 성보빌딩 지하1층,"6,300원 바스버거\r\n7,400원 바스치킨버거\r\n7,700원 하와이안버거\...",http://www.basburger.net/,http://facebook.com/basburger.kr/,http://www.instagram.com/basburger_/,...,96.741,88.163,78.5445,60.4285,59.385,50,50,[],6300 7400 7700 8700 9000,7820.000000
10,강남목장,"육류,고기요리",3177,맛있는녀석들,02-562-7003,서울 강남구 논현로86길 34\r\n지번역삼동 725-25 역삼포커스빌딩,"39,000원 업진살\r\n39,000원 생등심\r\n39,000원 생갈비살\r\n...",http://www.gncorral.com/,NaN,NaN,...,69.2964,88.3431,94.5031,52.1804,53.7858,44,56,['https://search.pstatic.net/common/?autoRotat...,39000 39000 39000 33000 39000,37800.000000
11,고갯마루,한식,36,NaN,NaN,서울 강남구 테헤란로28길 27\r\n지번역삼동 725-12,NaN,NaN,NaN,NaN,...,83.6435,89.5195,73.319,46.998,53.5835,48,52,[],,0.000000
12,샐러디 역삼점,"다이어트,샐러드",971,NaN,02-565-4066,서울 강남구 논현로85길 13\r\n지번역삼동 739 역삼동빌딩,"5,400원 콥 샐러디\r\n8,900원 아보카도연어 샐러디\r\n5,700원 시저...",http://www.saladykorea.com/,NaN,NaN,...,93.5813,74.0858,51.5311,39.5591,36.696,59,41,['https://search.pstatic.net/common/?autoRotat...,5400 8900 5700 6900 6900,6760.000000
13,마구로젠 역삼점,NaN,210,좋은아침,02-573-2777,서울 강남구 논현로86길 32\r\n지번역삼동 725-24 삼우빌딩,"80,000원 골드32,000원 점심참치특정식\r\n55,000원 스페셜\r\n68...",http://magurozen.modoo.at,NaN,NaN,...,64.208,86.6991,91.2693,52.8542,53.0422,41,59,['https://search.pstatic.net/common/?autoRotat...,80000 55000 68000 100000,75750.000000
14,강남보물섬,생선회,1177,NaN,02-566-3563,서울 강남구 테헤란로20길 11-1\r\n지번역삼동 736-19,"45,000원 모듬회(중)\r\n85,000원 모듬회(대)\r\n45,000원 광어...",NaN,NaN,NaN,...,72.8609,88.132,90.2231,56.0831,52.9236,43,57,[],45000 85000 45000 85000 55000,63000.000000
15,베이징코야 역삼동점,중식당,151,생생정보통,02-733-5292,서울 강남구 논현로86길 20\r\n지번역삼동 725-9 봉강빌딩 1층,"69,000원 북경오리 1마리\r\n30,000원 오리구이\r\n65,000원 특송...",NaN,NaN,NaN,...,73.6575,97.0895,87.5515,96.258,87.9475,44,56,['https://search.pstatic.net/common/?autoRotat...,69000 30000 65000 20000 30000,42800.000000
16,노아베이커리 GFC점,NaN,3591,NaN,02-558-4100,서울 강남구 테헤란로 152\r\n지번역삼동 737 B1,"2,900원 아메리카노",NaN,NaN,NaN,...,71.1493,53.3993,33.46,11.6507,10.186,60,40,['https://search.pstatic.net/common/?autoRotat...,2900,2900.000000
17,스타벅스 역삼역점,카페,106,NaN,02-758-8314,서울 강남구 테헤란로 145\r\n지번역삼동 646-15 우신빌딩,"4,100원 아메리카노(Tall)",http://www.istarbucks.co.kr/,http://www.facebook.com/starbuckskorea,http://www.instagram.com/starbuckskorea,...,91.4295,80.6485,67.282,51.5115,45.9655,56,44,['https://search.pstatic.net/common/?autoRotat...,4100,4100.000000
18,신동궁 역삼본점,감자탕,172,VJ특공대,02-555-3782,서울 강남구 테헤란로10길 11\r\n지번역삼동 823-41,"28,000원 감자탕(소)\r\n28,000원 뼈 숯불구이(소)\r\n28,000원...",NaN,NaN,NaN,...,94.3013,86.8404,70.3662,54.7493,53.4796,48,52,['https://search.pstatic.net/common/?autoRotat...,28000 28000 28000 7000 7000,19600.000000
19,가조쿠,일식당,1341,NaN,02-556-2177,서울 강남구 테헤란로25길 6-7\r\n지번역삼동 642-4 지하 1층,"6,500원 가케우동\r\n6,500원 붓가케우동\r\n9,500원 사케동\r\n1...",NaN,NaN,NaN,...,95.406,80.1545,70.457,57.8765,54.012,51,49,['https://search.pstatic.net/common/?autoRotat...,6500 6500 9500 13000,8875.000000
20,에그드랍 역삼점,샌드위치,321,NaN,02-566-1611,서울 강남구 논현로85길 52\r\n지번역삼동 735-17 1층 101호,"3,900원 베이컨 더블 치즈 샌드위치\r\n4,600원 아보홀릭 샌드위치\r\n2...",NaN,NaN,NaN,...,95.542,91.307,83.4525,53.879,54.5075,62,38,[],3900 4600 2900 3600 4400,3880.000000
21,루프탑 클라우드,NaN,777,NaN,02-2050-6035,서울 강남구 테헤란로25길 10\r\n지번역삼동 642,"270,000원 그레이 구스 SET\r\n260,000원 돈 훌리오 SET\r\n2...",http://urbandelight.co.kr/rooftop-kloud/,NaN,NaN,...,91.6644,78.5929,66.8844,50.0049,44.776,51,49,['https://search.pstatic.net/common/?autoRotat...,270000 260000 240000 30000 30000,166000.000000
22,모터시티,양식,542,NaN,02-2051-8877,서울 강남구 테헤란로 142\r\n지번역삼동 736-1,"23,900원 JACKSON 5\r\n23,900원 MANIMAL BBQ\r\n24...",http://www.instagram.com/motorcitykorea,http://www.facebook.com/motorcitykorea,NaN,...,87.303,87.2215,72.228,55.2575,58.0665,53,47,['https://search.pstatic.net/common/?autoRotat...,23900 23900 24900 17900 19800,22080.000000
23,롱브레드 베이커리,샌드위치,1561,NaN,02-566-1253,서울 강남구 테헤란로22길 15\r\n지번역삼동 736-44 건축문화사옥,"9,500원 롱브레드 파니니\r\n11,500원 연어 아보카도 샐러드\r\n8,50...",https://www.instagram.com/longbread_bakery,NaN,NaN,...,89.1658,79.6182,66.7191,45.7089,38.7182,59,41,['https://search.pstatic.net/common/?autoRotat...,9500 11500 8500 8800 8500,9360.000000
24,스시산원 청,"초밥,롤",176,NaN,02-538-5550,서울 강남구 논현로85길 52\r\n지번역삼동 735-20 역삼푸르지오시티 2층 2...,"50,000원 스시오마카세\r\n50,000원 점심\r\n80,000원 저녁",NaN,NaN,NaN,...,89.62,90.063,78.28,64.613,62.3855,45,55,[],50000 50000 80000,60000.000000
25,파크루안 역삼점,NaN,304,NaN,02-562-5565,서울 강남구 논현로 430\r\n지번역삼동 726 아세아빌딩 지하 1층,"8,000원 웰빙삼선콩자장면\r\n12,000원 왕갈비짬뽕\r\n23,000원 찹쌀...",http://www.parkruan.com,NaN,NaN,...,75.7975,82.545,86.066,98.874,97.309,46,54,['https://search.pstatic.net/common/?autoRotat...,8000 12000 23000 10000,13250.000000
26,생어거스틴 강남파이낸스점,NaN,2185,NaN,02-553-5101,서울 강남구 테헤란로 152\r\n지번역삼동 737 강남파이낸스센터,"18,000원 왕새우 팟타이\r\n15,000원 스파이시 타이 칠리 누들\r\n14...",http://www.augustin.co.kr/,NaN,NaN,...,93.68,84.908,64.6775,44.289,44.0895,54,46,['https://search.pstatic.net/common/?autoRotat...,18000 15000 14000 10000 37000,18800.000000
27,송추가마골 인어반 강남점,NaN,1045,NaN,02-554-9290,서울 강남구 테헤란로 134\r\n지번역삼동 735-3 포스코타워 역삼 지하 1층,"11,000원 뚝배기갈비탕\r\n39,000원 가마골갈비\r\n21,000원 한돈돼...",http://www.gamagoll.com/,https://www.facebook.com/scgamagoll/,http://www.instagram.com/scgamagoll/,...,63.355,83.448,91.68,83.211,95.1965,47,53,[],11000 39000 21000 9000 40000,24000.000000
28,연안식당 역삼점,"해물,생선요리",622,NaN,02-562-6092,서울 강남구 논현로85길 13\r\n지번역삼동 739 근영빌딩 2층,"변동\r\n꼬막비빔밥\r\n12,000원 꽃게살비빔밥\r\n12,000원 꽃게뚝배기...",http://yeonansikdang.co.kr/,NaN,NaN,...,71.153,86.883,94.627,77.377,72.3895,50,50,[],39000,39000.000000
29,교센,NaN,2967,NaN,02-501-2334,서울 강남구 테헤란로16길 9\r\n지번역삼동 735-29 1층,"45,000원 숙성회 코스 1인\r\n18,000원 간장새우\r\n20,000원 스...",NaN,NaN,NaN,...,76.99,90.7355,96.438,58.739,53.457,42,58,['https://search.pstatic.net/common/?autoRotat...,45000 18000 20000 20000 25000,25600.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4965,본 삼성차관아파트점 삼성중앙역,죽,2,NaN,02-555-0686,서울 강남구 봉은사로 474\r\n지번삼성동 117 쌍용 플래티넘,"11,000원 전복죽\r\n16,000원 트러플 전복죽\r\n15,000원 삼계전복...",http://www.bonjuk.co.kr/,NaN,NaN,...,67.9995,79.399,80.347,67.01,25,53,47,[],11000 16000 15000 13000 11000,13200.000000
4966,서초동연가 별관,"육류,고기요리",16,NaN,02-591-0281,서울 서초구 사평대로56길 14\r\n지번서초동 1302-39 동원빌딩 1층,"25,000원 전통육회\r\n40,000원 전통육회+사시미",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],25000 40000,32500.000000
4967,태영생막창 서울본점,"곱창,막창,양",252,NaN,NaN,서울 강남구 논현로38길 18\r\n지번도곡동 412-5,"12,000원 돼지생막창 150g\r\n16,000원 소막창 150g\r\n12,0...",NaN,NaN,NaN,...,72.7935,79.5435,79.4825,64.7665,25,47,53,[],12000 16000 12000,13333.333333
4968,마망갸또 신사동점,케이크전문,643,NaN,070-4353-5860,서울 강남구 압구정로10길 30-12\r\n지번신사동 524-27,"5,500원 카라멜 롤케이크\r\n5,500원 카라멜사케라떼\r\n6,500원 오레...",http://www.mamangt.com/,NaN,NaN,...,97.3677,76.3343,52.6253,39.964,36.1957,63,37,['https://search.pstatic.net/common/?autoRotat...,5500 5500 6500,5833.333333
4969,문어세상 양재점,"해물,생선요리",31,모닝와이드,02-575-0995,서울 서초구 강남대로 188\r\n지번양재동 15-3 화승빌딩,"120,000원 해천탕(닭) 스페셜\r\n100,000원 해천탕(닭) 對\r\n80...",NaN,NaN,NaN,...,50.3465,78.367,92.762,91.4915,93.827,40,60,[],120000 100000 80000 120000 100000,104000.000000
4970,마봉 논현언주역점,양꼬치,26,NaN,02-518-1515,서울 강남구 봉은사로29길 13\r\n지번논현동 234-3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],,0.000000
4971,메차쿠차 강남역점,일식당,81,NaN,02-3481-3767,서울 서초구 강남대로69길 11\r\n지번서초동 1308-1 삼미빌딩,"8,000원 우동정식\r\n9,000원 김치나베돈가스\r\n10,000원 모밀정식\...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],8000 9000 10000 8000 8000,8600.000000
4972,참숯주먹생고기,"육류,고기요리",9,NaN,02-6401-5132,서울 강남구 역삼로1길 20\r\n지번역삼동 831-31 2층,"35,000원 한우등심\r\n25,000원 진갈비살\r\n15,000원 안창살\r\...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],35000 25000 15000 10000 11000,19200.000000
4973,바나프레소 대치은마점,카페,71,NaN,070-8998-8921,서울 강남구 도곡로 451\r\n지번대치동 941-22 한나빌딩 1층,"1,500원 아메리카노",http://www.instagram.com/banapresso,NaN,NaN,...,77.393,52.2345,96.6265,74.5405,25,60,40,[],1500,1500.000000
4974,해우름,생선회,27,NaN,02-6080-1113,서울 서초구 바우뫼로37길 38\r\n지번양재동 16-1,"9,000원 낙지볶음\r\n25,000원 활어숙성회 스페셜\r\n40,000원 활어...",NaN,NaN,NaN,...,64.83,88.363,92.0155,80.56,78.4745,40,60,[],9000 25000 40000 15000 25000,22800.000000
4975,삼국지,중식당,25,NaN,02-549-2339,서울 강남구 언주로134길 6\r\n지번논현동 115-22,NaN,http://blog.naver.com/kkajc3/110138973966,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['https://search.pstatic.net/common/?autoRotat...,,0.000000
4976,부산아지매 학동역점,국밥,28,NaN,02-553-9882,"서울 강남구 학동로 165\r\n지번논현동 58-2 마일스디오빌 1층 112,113호","7,000원 아지매국밥",http://www.busanajimae.com/,https://www.facebook.com/busan9882/,https://www.instagram.com/busan_ajimae/,...,86.2695,80.522,71.568,57.4355,25,47,53,[],7000,7000.000000
4977,짝꿍,떡볶이,541,NaN,02-537-6836,서울 서초구 서초대로53길 7\r\n지번서초동 1695-7 효성빌딩 지하 1층 짝꿍떡볶이,"12,000원 2인세트\r\n21,000원 4인세트\r\n4,000원 1인추가\r\...",NaN,NaN,NaN,...,86.216,83.0185,78.9125,46.0315,45.0555,58,42,['https://search.pstatic.net/common/?autoRotat...,12000 21000 4000 4500 5000,9300.000000
4978,커피빈 삼성전자강남사옥점,카페,4,NaN,02-2055-1142,서울 서초구 서초대로74길 11\r\n지번서초동 1320-10 삼성전자 서초사옥,"4,800원 아메리카노 S\r\n5,300원 카페라떼 S",http://www.coffeebeankorea.com/,http://www.facebook.com/thecoffeebeankorea,http://www.instagram.com/coffeebeankorea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],4800 5300,5050.000000
4979,진고래,한식,8,NaN,02-566-0231,서울 강남구 선릉로86길 18\r\n지번대치4동 897-22,"27,000원 참복지리.탕\r\n60,000원 참복불고기\r\n60,000원 참복찜...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],27000 60000 60000 48000 58000,50600.000000
4980,멜리멜로,베이커리,711,NaN,02-588-2435,서울 서초구 사임당로19길 6\r\n지번서초동 1648-2 1층 멜리멜로,"2,400원 휘낭시에\r\n9,000원 심쿵멜로\r\n4,000원 아메리카노\r\n...",http://instagram.com/melimelo.dessert,NaN,NaN,...,93.293,78.6215,64.2775,48.4755,49.213,61,39,['https://search.pstatic.net/common/?autoRotat...,2400 9000 4000 4500 7900,5560.000000
4981,겟 올라잇바(BAR),바(BAR),106,NaN,010-3065-0895,서울 강남구 도산대로57길 18\r\n지번청담동 89-5,"340,000원 Glenfiddich 12y\r\n340,000원 Balvenie ...",http://instagram.com/getallright.cheongdam/,NaN,NaN,...,95.8258,95.2178,73.6093,48.6404,53.2213,53,47,[],340000 340000 340000 340000 340000,340000.000000
4982,더 트리하우스바(BAR),바(BAR),1095,NaN,02-556-2017,서울 강남구 삼성로104길 21\r\n지번삼성동 148-13 5층,변동\r\nClassic Cocktail\r\n변동\r\nWhiskey,http://blog.naver.com/thetreehouse2017,NaN,NaN,...,91.261,81.915,70.1715,46.0745,25,49,51,['https://search.pstatic.net/common/?autoRotat...,,0.000000
4983,청춘극장 쪽갈비,"육류,고기요리",65,NaN,02-555-2133,서울 강남구 봉은사로72길 6\r\n지번삼성동 115-32,"15,000원 양념쪽갈비\r\n15,000원 매운쪽갈비\r\n14,000원 항정껍데...",https://chungchun6161.modoo.at,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],15000 15000 14000 9000 9000,12400.000000
4984,이비스스타일앰배서더강남 프레쉬365다이닝,NaN,1637,NaN,02-3011-8120,서울 강남구 삼성로 431\r\n지번대치동 893-1 이비스 스타일 앰배서더 강남 ...,"22,000원 조식뷔페\r\n35,000원 런치 뷔페\r\n45,000원 주말 런치...",https://www.ambatel.com/ibisstyles/gangnam/ko/...,NaN,NaN,...,77.525,88.8915,93.1235,74.8805,74.6155,51,49,['https://search.pstatic.net/common/?autoRotat...,22000 35000 45000 45000 49000,39200.000000
4985,자금성,중식당,181,NaN,050-4109-2917,서울 강남구 학동로67길 7\r\n지번청담동 44-7,"6,000원 짜장면\r\n6,500원 짬뽕\r\n20,000원 탕수육\r\n21,0...",http://412017.4tong.co.kr/service1/,NaN,NaN,...,57.6929,69.0431,84.8333,91.3889,74.1827,49,51,['https://search.pstatic.net/common/?autoRotat...,6000 6500 20000 21000 7000,12100.000000
4986,우와,일식당,4525,NaN,070-8833-7336,서울 강남구 강남대로158길 17\r\n지번신사동 508-8 1층,"12,500원 돼지오코노미야끼&야끼소바\r\n16,000원 철판 꽃갈비살 100g\...",NaN,NaN,NaN,...,89.8076,71.4373,53.7742,45.9307,40.8276,54,46,[],12500 16000 13500 14500 5000,12300.000000
4987,스테프핫도그 선릉역점,NaN,81,NaN,02-2183-1097,서울 강남구 테헤란로 322\r\n지번역삼동 707-34 한신인터밸리24빌딩 B113호,"5,700원 스테프 핫도그\r\n5,500원 치즈 온 불고기\r\n6,600원 치즈...",NaN,NaN,NaN,...,89.122,77.5855,67.11,36.5705,25,55,45,[],5700 5500 6600 5500 6600,5980.000000
4988,할리스커피 학동역점,카페,19,NaN,070-4700-6699,서울 강남구 학동로 219\r\n지번논현동 89-22 국제빌딩,"4,100원 카페 아메리카노\r\n4,600원 카페 라떼\r\n5,400원 바닐라 ...",http://www.hollys.co.kr/,https://www.facebook.com/EnjoyHollys,https://www.instagram.com/hollyscoffeekr,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],4100 4600 5400 5900 5500,5100.000000
4989,뻐꾸기,포장마차,202,NaN,02-512-6798,서울 강남구 도산대로17길 4\r\n지번신사동 561-17,"16,000원 통마늘 닭똥집\r\n17,000원 낙지 떡볶이\r\n17,000원 알...",NaN,NaN,NaN,...,93.964,74.5267,56.3036,39.6729,43.6911,55,45,['https://search.pstatic.net/common/?autoRotat...,16000 17000 17000 12000 16000,15600.000000
4990,테이블스푼 청담점,"도시락,컵밥",205,NaN,02-518-3585,서울 강남구 선릉로 660\r\n지번삼성동 8-2 브라운스톤 레전드상가 1층 113호,"8,000원 한입도시락_단품A\r\n10,000원 한입도시락_단품B\r\n20,00...",http://tbspchungdahm.modoo.at/,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['https://search.pstatic.net/common/?autoRotat...,8000 10000 20000 25000 5000,13600.000000
4991,송탄부대찌개본점,"찌개,전골",133,NaN,02-541-2446,서울 강남구 도산대로 166\r\n지번논현동 7-1,"12,000원 특부대찌개\r\n12,000원 만두부대찌개\r\n12,000원 카레부...",http://blog.naver.com/songtanbudae,NaN,NaN,...,85.106,87.1045,85.129,65.5595,66.2855,48,52,['https://search.pstatic.net/common/?autoRotat...,12000 12000 12000 44000 34000,22800.000000
4992,서초생곱창,"곱창,막창,양",51,NaN,02-583-5663,서울 서초구 서초대로54길 11\r\n지번서초동 1670-1,"23,000원 곱창1인분\r\n24,000원 소 양구이 1인분\r\n18,000원 ...",NaN,NaN,NaN,...,82.1595,81.914,83.847,66.5935,70.0575,49,51,[],23000 24000 18000 18000 5000,17600.000000
4993,마이디어,케이크전문,10,NaN,010-9959-0525,서울 강남구 강남대로118길 55\r\n지번논현동 180-16 세림빌딩 2층,"40,000원 레터링 케이크\r\n85,000원 플라워 케이크",https://www.instagram.com/mydearcake_korea,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['https://search.pstatic.net/common/?autoRotat...,40000 85000,62500.000000
4994,영동회관,"육류,고기요리",103,NaN,02-6084-0250,서울 서초구 강남대로30길 28\r\n지번양재동 17-1 1층,"12,000원 급냉 삼겹살\r\n7,000원 청국장찌개\r\n12,000원 키조개 ...",NaN,NaN,NaN,...,64.386,85.9535,84.239,66.8435,25,44,56,[],12000 7000 12000 7000,9500.000000

In [1]:
df.to_csv("네이버맛집_전처리.csv", index=False, encoding='utf-8-sig')

NameError: name 'df' is not defined

# 가격대 컬럼 추가

In [16]:
for i, df_Menu in enumerate(df.Menu):
    df.loc[i, 'Price'] = re.sub(',', '', df_Menu) + '\r\n'

In [17]:
for i, df_Price in enumerate(df.Price):
    df.loc[i, 'Price'] = re.sub('원.*\n|~', ' ', df_Price)

In [18]:
for i, df_Price in enumerate(df.Price):
    df.loc[i, 'Price'] = re.sub('.*\n', '', df_Price)

In [19]:
df.loc[:,'Avr'] = 0

In [20]:
for j, df_Avr in enumerate(df.Avr):
    sum = 0
    try:
        for i in df.Price[j].strip().split(' '):
            sum += int(i)
        df.loc[j, 'Avr'] = sum/len(df.loc[j, 'Price'].strip().split(' '))
    except:
        df.loc[j, 'Avr'] = sum